---
title: "Thoughts on modeling after reading and doing a little bit of EDA"
output: html_document
---

I think I'd come down on the side of modeling the survival data set. Modeling the natality data set is akin to the "zombie" model because a female without a pup in year $j$ would be a 0 but if she had a pup in year $j + 1$, she'd be a 1 (but that does *not* imply that her 'true state' in year $j$ was a 1).

### Thoughts for using survival data set:

- We could (possibly) estimate the probability of survival (strictly decreasing) and the probability of returning to San Miguel Island (not necessarily decreasing). 

### Issues

- They aren't limited to only one site per year - for those who we know switched, we may have to pick an arbitrary cut off or use the mode. We have almost 25% of the data set (individual-year pairs) that have more than one 'sitecode'.
- This model would still be closed to immigration (hence why we wouldn't really be estimating the abundance of the SMI population)
- They had observations every day from 'late May' to 'early August' ... not exactly confidence inspiring in choosing an $n$ for the binomial. 
- There's no option for going to a site other than the 3 observed sites (if we restict inference to just SMI, I don't think this is necessarily a problem)
- Assumes that the probability of choosing a site doesn't depend on the site it chose the previous year (may or may not be realistic?)

\begin{aligned}
  y_{i \cdot} &\sim \begin{cases}
      0 & z_{ij} = 0 \\
      0 & z_{ij} = 1 \\
      \text{Binomial}(n,p_{ij}) & z_{ij} = 2
      \end{cases} \\
  &\text{for $z_{i,j-1} \neq 0$:} \\
  z_{ij} &\sim \text{Multinomial}(1, \theta) \qquad \text{...how do you make bold greek letters in markdown?} \\
  \theta_k &= \frac{w_k}{\sum_{l=1}^3 w_l} \\
  \mathbf{w} &= \mathbf{X}\beta \\
  \beta &\sim \text{N}(\mu_\beta, \sigma_\beta I)\\
  &\text{for $z_{i,j-1} = 0$:} \\
  z_{ij} &= 0
\end{aligned}
